/*****************************************************************************/
/*                                                                           */
/* FILENAME                                                                  */
/* 	 filtercoefficients.h                                                    */
/*                                                                           */
/* DESCRIPTION                                                               */
/*   contains the FIR filter coefficients                                    */
/*                                                                           */
/* REVISION                                                                  */
/*   Revision: 2.00	                                                         */
/*   Author  : Marc Geilen                                                   */
/*---------------------------------------------------------------------------*/
/*                                                                           */
/* HISTORY                                                                   */
/*   Revision 1.00                                                           */
/*   1st June 2016.                                                          */
/*   Revision 2.00                                                           */
/*   7th June 2019.                                                         */
/*                                                                           */
/*****************************************************************************/

#ifndef FILTERCOEFFICIENTS_H_
#define FILTERCOEFFICIENTS_H_

#include <stdint.h>

/*****************************************************************************/
/* Low Pass Filter Coefficients                                              */
/*****************************************************************************/

// The code below is automatically generated by the Matlab script firdesign.m
// It is an 24th order (length 25) low pass FIR filter with cutoff frequency 500Hz.
// It is for a digital system with a sampling frequency of  44.1kHz.
// The generated filter coefficients are the integer representations of fixed point
// numbers in the representation: Q(16,8).
#define FIR_FILTER_LENGTH 25
#define FIR_FRACTIONAL_BITS 8
const int16_t FIRFilterCoefficients[FIR_FILTER_LENGTH] = {
	1, 2, 3, 4, 6, 8, 10, 13, 
	15, 17, 19, 20, 20, 20, 19, 17, 
	15, 13, 10, 8, 6, 4, 3, 2, 
	1
};

#endif /*FILTERCOEFFICIENTS_H_*/
